obj = open("Mytext.txt", "w")
obj.write("Hello world \n")
obj.close()
obj = open("Mytext.txt", "r")
data=obj.read()
print(len(data))
obj.close()
obj = open("Mytext.txt", "a")
obj.write("10")
obj.close()